spring:
  application:
    name: @name@
    description: @description@
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
---
management:
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
---
server:
  port: @server.port@
---
restTemplate:
  networkTimeout: 3000
---
converterIp:
  nat64prefix: "2a04:4a00:5:10ff:4:1:"
---
restTemplate:
  requestTimeout: 60000
  poolTimeout: 10000
  connectionTimeout: 10000
  maxTotalPooling: 200
  defaultMaxPerRoute: 200
---
adapter-cashreg:
  url: "https://online.atol.ru/possystem/v4/"
---
time:
  config:
    maxTimePolling: 600
    pollingDelay: 600
---
error-mapping:
  file: classpath:fixture/errors.json
  patternReason: "'%s' - '%s'" # 'code' - 'description'
